### ISSUE TITLE
Navigator. How can I disable the back button in browser.

### ISSUE THREAD

**Issue by yunyang100** [iampawan/VelocityX#100]
I have used the clearAndPush(), removeLastUri(), even popToRoot(), but when I click the back button, It still back to the last URL. I also used WillPopScope but it still not work.

Is there have a way to disable the browser's back and forward button for right now?

**Comment by pragmatically-dev** [comment]
Yeah! I'm with s similar issue, I need to guard the login path

**Comment by iampawan** [comment]
Unfortunately, flutter web has some limitations and it's tough to handle those scenerios. I am working on it. But you can use 

```
 '/safe_route': (uri,_) {
  if (!isLoggedIn()) return VxRoutePage(pageName: "Home", child: HomePage());
  return LoginPage();
}
```

**Comment by yunyang100** [comment]
> Unfortunately, flutter web has some limitations and it's tough to handle those scenerios. I am working on it. But you can use
> 
> ```
>  '/safe_route': (uri,_) {
>   if (!isLoggedIn()) return VxRoutePage(pageName: "Home", child: HomePage());
>   return LoginPage();
> }
> ```

Thank you very much. I will try this way.
