### ISSUE TITLE
context.vxNav.pop() doesnt pop 

### ISSUE THREAD

**Issue by jayyrivera** [iampawan/VelocityX#106]
**Describe the bug**
I have a loading  dialog widget which will show after clicking login and needs to be pop after receiving the return true but the i am experiencing context.vxNav.pop() showing cannot pop but when i use Navigator.pop(context) it pops;

**To Reproduce**
void login() async {
    if (_formKey.currentState!.validate()) {
      iosLoading(context);

      var res = await context
          .read<LoginProvider>()
          .emailLogin(email!.text, password!.text);

      if (res == true) {
        Navigator.of(context).pop();
        await VxNavigator.of(context).clearAndPush(Uri(path: Dashboard));
        passwordNode?.unfocus();
        emailNode?.unfocus();
      } else if (res == false) {
        Navigator.of(context).pop();

        await VxNavigator.of(context).push(
          Uri(path: UpdateProfile),
        );
      } else {
        Navigator.of(context, rootNavigator: true).pop();
        showAlertDialog(context, res);
      }
    }
  }

**Expected behavior**
It should pop the iosloading dialog but i changed it to Navigator.pop to pop the dialog;

**Smartphone (please complete the following information):**
 iphone simulator
Xiaomi mi 9t

**Comment by iampawan** [comment]
vxNav is only for routing of pages, it won't work with dialogs

**Comment by jayyrivera** [comment]
ahh yes, my bad for reporting an issue.

**Comment by iampawan** [comment]
No, actually your issue is valid but it behaves differently because vxNav uses Navigator 2.0

**Comment by jayyrivera** [comment]
i realized it lately when i was exploring velocity_x's nav2. I got used to with nav1
