### ISSUE TITLE
[vxObserver] Implement with FirebaseAnalyticsObserver

### ISSUE THREAD

**Issue by Philip-soon** [iampawan/VelocityX#108]
**Is your feature request related to a problem? Please describe.**

We are currently using VelocityX for Navigation 2.0 and about to implement Firebase Analytics.

Although, I was able to find VxObserver which is extended from NavigatorObserver, implementing FirebaseAnalyticsObserver wasn't straightforward. Has anyone implemented Analytics successfully? If so, can anyone please share an example?

**Comment by iampawan** [comment]
It's a very specific request and I don't have any example for this usecase. So maybe a better way will be to ask on some other forum. Closing this for now
