### ISSUE TITLE
[Feature] Add extension to create Table widget in VelocityX.

### ISSUE THREAD

**Issue by AyushBherwani1998** [iampawan/VelocityX#110]
## Description

Currently, it takes a quite a work to create  a Table in Flutter, maybe we can simplify the APIs in VelcoityX.  For example, 

```dart
<TableRow>[<Widget>[], <Widget>[]].table.make()
``` 
can be equivalent to 

```dart
Table(
  children: <TableRow>[
    TableRow(
      children: <Widget>[],
    ),
    TableRow(
      children: <Widget>[],
    ),
  ]
)
```

Addition to this, we can try to simplify it more.

**Comment by iampawan** [comment]
Added in v3.3.0
