### ISSUE TITLE
Conflict VelocityX and EasyLocalization with locale context extension.

### ISSUE THREAD

**Issue by VasiliyRusin** [iampawan/VelocityX#114]
**Describe the bug**

**To Reproduce**
1. Install `VelocityX` and `EasyLocalization`.
2. Setup both.
3. Get conflict `locale` error.

**Expected behavior**
As it would be a breakable change to just remove `locale`, I think we should have the `hasCustomLocalization` flag. For disabling `locale` if it needs to use custom localization.

**Additional context**
```
    ../../../.pub-cache/hosted/pub.dartlang.org/velocity_x-3.3.0/lib/src/extensions/context_ext.dart:191:15: Context: This is one of the extension members.
      Locale? get locale => Localizations.localeOf(this);
                  ^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/easy_localization-3.0.0/lib/src/public_ext.dart:105:14: Context: This is one of the extension members.
      Locale get locale => EasyLocalization.of(this)!.locale;
                 ^^^^^^
```

https://github.com/iampawan/VelocityX/blob/18c1882d4969305513b020d1b6a393fc51512a7d/lib/src/extensions/context_ext.dart#L191

**Comment by iampawan** [comment]
There can be workarounds but I think I should remove those extensions.

**Comment by VasiliyRusin** [comment]
> There can be workarounds but I think I should remove those extensions.

I think it major change if someone uses it in production it brokes the project.

**Comment by VasiliyRusin** [comment]
Also if you know a workaround, please write an example, it helps a lot.

**Comment by denes16** [comment]
Any workaround?
