### ISSUE TITLE
VxTextField Validation style is weird

### ISSUE THREAD

**Issue by shinewanna** [iampawan/VelocityX#116]
**To Reproduce**
1. Use VxTextField VxTextFieldBorderType.roundLine
2. And validate the textfield

**Expected behavior**
Validate like round red line and validate text

**Screenshots**
**Before Validate**
![2](https://user-images.githubusercontent.com/39454969/123060857-1d993d00-d431-11eb-81a3-15d78d56060e.jpeg)

**When Validate**
![1](https://user-images.githubusercontent.com/39454969/123060876-212cc400-d431-11eb-8bec-55397df05a8e.jpeg)

**Comment by UtkarshA135** [comment]
@iampawan  can I take up this issue

**Comment by iampawan** [comment]
Yes sure

**Comment by AshishSingh2001** [comment]
@iampawan  I fixed the issue in my previous PR #125  can you review and maybe give feedback on it
