### ISSUE TITLE
Nested waitAndPush with returnAndPush raise exception

### ISSUE THREAD

**Issue by carmas123** [iampawan/VelocityX#119]
When we use `waitAndPush` to open a detail and return the result with `returnAndPush` to pop the detail result all work fine, but if from detail page we open a subdetail that use again `waitAndPush` and `returnAndPush` I got an exception from the first `returnAndPush`.

MAIN 
  -> "waitAndPush" -> DETAIL
    -> "waitAndPush" -> SUB-DETAIL
        ...
    <- "returnAndPush" - THIS WORK
  <- "returnAndPush" - Future already completed

**Comment by Zahra-H** [comment]
any solution? i came across it too

**Comment by iampawan** [comment]
Fixed with v3.5.0

**Comment by carmas123** [comment]
Fantastic
