### ISSUE TITLE
Clear and Push not working as expected in browser

### ISSUE THREAD

**Issue by rutaba1** [iampawan/VelocityX#120]
Hi. I am trying to implement navigation on web and for some reason when I use VxNavigator.of(context).clearAndPush method  it doesn't remove all the pages and when I press the back button on browser it takes me to the previous screen. I tried using this function for guarded routes 
```
RoutesConstants.selectOrganisation : (uri, params) {
        if(mainScreenProvider.isUserAuthenticated){
          return VxRoutePage(pageName: "selectOrg",child: SelectOrgainsation());
        }
          uri.replace(path: RoutesConstants.login);
        return VxRoutePage(pageName: "login",child: LoginScreen());
      },
```
And it takes me to the login screen but  the url on search bar is not updating to login url. Is there a way to literally remove all pages from route stack and start fresh so that back button is disabled?

**Comment by iampawan** [comment]
Navigation on the web is tricky in some cases. If you will provide me a working example with the issue, I can dig more and can help you out.

**Comment by AhemadAbbasVagh** [comment]
Hello Team any updates on this? I am facing the same issue.

In my case... Once the user is logged out then I am checking using guard if user is logged out then user should not be pushed on home page. but still user is pushed on home page and this only happens when user tries to access forward and backward in browser

**Comment by iampawan** [comment]
Closing this as Vx doesn't support navigation anymore. Use go_router or any other package for that
