### ISSUE TITLE
Add support for text shadow

### ISSUE THREAD

**Issue by manikantag** [iampawan/VelocityX#127]
**Is your feature request related to a problem? Please describe.**
Add support for text shadow

**Describe the solution you'd like**
```
'Sample text with shadow'.text.shadow(offsetX, offsetY, blurRadius, color).make();
```
or, even better with shadow size variations, like `shadowlg(color)` and `shadowsm(color)`

**Describe alternatives you've considered**
Tried setting `.textStyle()` for shadow, but is conflicting with `.header2()` option.

**Comment by delikin** [comment]
Done. Hope it helps

**Comment by iampawan** [comment]
https://github.com/iampawan/VelocityX/pull/129 fixes this
