### ISSUE TITLE
VxBadge - Ellipse

### ISSUE THREAD

**Issue by carmas123** [iampawan/VelocityX#132]
The VxBadge as type ellipse must be constrained with minimum width as badge height like this:

I see into VxRound widget at base of VxBadge that the code when we make the container is wrong at row 62:

```
 Container(
        height: tempSize,
```
![image](https://user-images.githubusercontent.com/6574219/135645849-188f44ff-ad80-45ff-841d-89da9e8e99f7.png)

must became 
```
Container(
      constraints: BoxConstraints(maxHeight: tempSize, minHeight: tempSize, minWidth: tempSize),
```
![image](https://user-images.githubusercontent.com/6574219/135645928-aa10effd-431d-4a26-852a-b4b5b79d4a49.png)

this will allow you not to have an oval circle when creating the badge.

**Comment by iampawan** [comment]
I’ll fix this
