### ISSUE TITLE
allow pages to stop from navigating away, e.g. if there are unsaved state changes

### ISSUE THREAD

**Issue by jamolina2021** [iampawan/VelocityX#137]
Hello,
I am going to start a web project with Flutter, for another project use the Fluro library, however, I could not solve the following problem:
If a user is on a page that contains a form and is making modifications is said form, I would like that if he tries to exit without having saved the modifications (either by putting another url, with the browser's backbutton, ...) it would show him an alertdialog giving him the possibility of canceling the navigation to the new url or, on the contrary, of canceling the modifications and staying on the same page where he is.
The question is, can I do this with VelocityX?
VelocityX has any mechanism by which this functionality can be achieved?
Please, if this functionality is possible with VelocityX could you give me some indications.
Thank you so much for all the help.
Regards,
Jose

**Comment by iampawan** [comment]
Hi Jose. there are still many issues with Navigations on Flutter web and VX also doesn't offer such functionality as of now
