### ISSUE TITLE
Not a subtype exception has been thrown when navigating from login page (with LoginVxStore) to the home page (with MainVxStore)

### ISSUE THREAD

**Issue by ying8599** [iampawan/VelocityX#138]
**Describe the bug**
When navigating to the Home page through VxNotifier, the system throws an exception "type 'MainVxStore' is not a subtype of type 'LoginVxStore' in type cast". 
Navigation method: ctx.vxNav.clearAndPush(Uri.parse("/home")); (Navigator 2.0)

**To Reproduce**
1. Create two pages with VxStore
2. Navigate to the second page after mutation by VxNotifier by using the VxNavigator.
3. System throws an exception "type 'MainVxStore' is not a subtype of type 'LoginVxStore' in type cast". 

**Expected behavior**
Should navigate without any exception.

**Screenshots**
Exception:
![image](https://user-images.githubusercontent.com/53040824/149075298-d664ed14-6da0-4bac-b0a3-fbe620fb4f9f.png)

Exception point to:
![image](https://user-images.githubusercontent.com/53040824/149075435-d46c4982-f8ec-40ee-b07d-b61847e5a221.png)

VxNotifier:
![image](https://user-images.githubusercontent.com/53040824/149075362-87d90b68-0b02-4380-88a2-85f19c782c9a.png)

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 10 (API 29)

**Comment by iampawan** [comment]
How you are specifying your login store and mainstore?

**Comment by ying8599** [comment]
My fault, I overlook the documentation, which is only one store is allowed.
I remove the < T > and declare it separately and the problem is solved.
But I had changed the method and add the instance to the store.

**Comment by iampawan** [comment]
Awesome
