### ISSUE TITLE
createstate conflicts error not able to run or build my app 

### ISSUE THREAD

**Issue by hostusservices** [iampawan/VelocityX#140]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/animated/animated_height.dart:25:25: Error: Can't declare a member that conflicts with an inherited one.
  State<StatefulWidget> createState() {
                        ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/appbar.dart:294:18: Error: Can't declare a member that conflicts with an inherited one.
  _VxAppBarState createState() => _VxAppBarState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/common/velocity_ensure_visible.dart:54:36: Error: Can't declare a member that conflicts with an inherited one.
  _VxEnsureVisibleWhenFocusedState createState() =>
                                   ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/common/velocity_zero.dart:66:20: Error: Can't declare a member that conflicts with an inherited one.
  _VxZeroCardState createState() => _VxZeroCardState();
                   ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/common/velocity_zero.dart:263:31: Error: Can't declare a member that conflicts with an inherited one.
  _PKCardProfileSkeletonState createState() => _PKCardProfileSkeletonState();
                              ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/common/velocity_zero.dart:414:28: Error: Can't declare a member that conflicts with an inherited one.
  _PKCardPageSkeletonState createState() => _PKCardPageSkeletonState();
                           ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/dialog.dart:318:22: Error: Can't declare a member that conflicts with an inherited one.
  VxTimerButtonState createState() => VxTimerButtonState();
                     ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/drawer.dart:124:18: Error: Can't declare a member that conflicts with an inherited one.
  _VxDrawerState createState() => _VxDrawerState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/gesture.dart:300:24: Error: Can't declare a member that conflicts with an inherited one.
  _CallbackButtonState createState() => _CallbackButtonState();
                       ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/marquee.dart:33:18: Error: Can't declare a member that conflicts with an inherited one.
  VxMarqueeState createState() => VxMarqueeState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/pinview.dart:78:18: Error: Can't declare a member that conflicts with an inherited one.
  VxPinViewState createState() => VxPinViewState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/popup_menu.dart:83:21: Error: Can't declare a member that conflicts with an inherited one.
  _VxPopupMenuState createState() => _VxPopupMenuState();
                    ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/preview.dart:84:19: Error: Can't declare a member that conflicts with an inherited one.
  _VxPreviewState createState() => _VxPreviewState();
                  ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/random.dart:26:21: Error: Can't declare a member that conflicts with an inherited one.
  _VxRandomBoxState createState() => _VxRandomBoxState();
                    ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/rating.dart:70:18: Error: Can't declare a member that conflicts with an inherited one.
  _VxRatingState createState() => _VxRatingState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/shimmer.dart:66:19: Error: Can't declare a member that conflicts with an inherited one.
  _VxShimmerState createState() => _VxShimmerState();
                  ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/skeleton.dart:62:19: Error: Can't declare a member that conflicts with an inherited one.
  VxSkeletonState createState() => VxSkeletonState();
                  ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/stepper.dart:54:18: Error: Can't declare a member that conflicts with an inherited one.
  VxStepperState createState() => VxStepperState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/swiper.dart:227:18: Error: Can't declare a member that conflicts with an inherited one.
  _VxSwiperState createState() => _VxSwiperState();
                 ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/textfield.dart:100:21: Error: Can't declare a member that conflicts with an inherited one.
  _VxTextFieldState createState() => _VxTextFieldState();
                    ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/timeline/timeline_widget.dart:36:20: Error: Can't declare a member that conflicts with an inherited one.
  _VxTimelineState createState() {
                   ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/toast.dart:168:21: Error: Can't declare a member that conflicts with an inherited one.
  _VxToastViewState createState() => _VxToastViewState();
                    ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-3.4.0/lib/src/flutter/widgets.dart:369:25: Error: Can't declare a member that conflicts with an inherited one.
  State<StatefulWidget> createState() => _KeepAliveState();
                        ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/vxstate-2.1.0/lib/src/widgets/vxconsumer.dart:29:20: Error: Can't declare a member that conflicts with an inherited one.
  _VxConsumerState createState() => _VxConsumerState<T>();
                   ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/vxstate-2.1.0/lib/src/widgets/vxnotifier.dart:28:20: Error: Can't declare a member that conflicts with an inherited one.
  _VxNotifierState createState() => _VxNotifierState();
                   ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin
            ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/auto_size_text_pk-3.0.0/lib/src/auto_size_text.dart:216:22: Error: Can't declare a member that conflicts with an inherited one.
  _AutoSizeTextState createState() => _AutoSizeTextState();
                     ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:791:13: Context: This is the inherited member.
  State get createState; // ignore: no_logic_in_create_state, this is the original sin

**Comment by hostusservices** [comment]
need help urjently for my project (i am following the video 8 hours of flutter )
![image](https://user-images.githubusercontent.com/47149951/154702640-3944beb3-6277-489c-b713-1871c14981ce.png)

**Comment by hostusservices** [comment]
when removing the velocity x dependency my app is working fine please solve the issue i want to use this velociy x in my all projects

**Comment by iampawan** [comment]
I am not able to reproduce it. Can you share some sample code?

**Comment by hostusservices** [comment]
I developing a web application on flutter latest version but the velocity X
plugin was giving me error so I skip it and choose other available options.
So I cannot provide u the sample code. Please update your plugin for web
development . Then please let me know. Because I like your plugin very much
but right now it's useless for me. I have many future projects that I
really like to use your plugin

Thankyou very much to reply me.
