### ISSUE TITLE
Can't get param values with vxNav.push()

### ISSUE THREAD

**Issue by ebiboy2** [iampawan/VelocityX#156]
Cant' seem to figure out why I can't get the values to items when I call `context.vxNav.push(Uri(path: '/completeOrder'), params: item);`
Value exists but appears as null in the other screen.

**Comment by iampawan** [comment]
Can you add a sample?

**Comment by ebiboy2** [comment]
I am trying to get the value using `context.vxNav.params`

**Comment by iampawan** [comment]
Closing this as Vx doesn't support navigation anymore. Use go_router or any other package for that
