### ISSUE TITLE
device_preview ^1.1.0 and velocity_x ^1.4.1, version solving failed.

### ISSUE THREAD

**Issue by ayushkadbe** [iampawan/VelocityX#157]
**Describe the bug**
Can't use velocity_x if myapp is already using device_preview package.

**To Reproduce**
1. Use device_preview package in myapp: https://pub.dev/packages/device_preview
2. Add velocity_x dependency in pubspec.yaml, import package on any homepage.dart
3. Run flutter pub get
4. See error:
 ```
$flutter pub get
Because velocity_x >=0.5.0 <2.0.0-nullsafety.0 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0, velocity_x >=0.5.0 <2.0.0-nullsafety.0 is incompatible with flutter_localizations from sdk.
And because device_preview 1.1.0 depends on flutter_localizations from sdk and no versions of device_preview match >1.1.0 <2.0.0, velocity_x >=0.5.0 <2.0.0-nullsafety.0 is incompatible with device_preview ^1.1.0.
So, because myapp depends on both device_preview ^1.1.0 and velocity_x ^1.4.1, version solving failed.
Running "flutter pub get" in myapp...                                   
pub get failed (1; So, because myapp depends on both device_preview ^1.1.0 and velocity_x ^1.4.1, version solving failed.)
 ```

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Parrot OS 5.0
 - Browser: chrome, brave
 - Version:  
   KDE Plasma Version: 5.20.5
   KDE Framework Version: 5.78.0
   Kernel Version: 5.18.0-1parrot1-amd64
   OS Type: 64 bit
    

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iampawan** [comment]
You can override the dependencies to fix it. VelocityX is using the latest version of intl package so no issue from our side.
