### ISSUE TITLE
How to provide values like a prop (like in react)?

### ISSUE THREAD

**Issue by milindgoel15** [iampawan/VelocityX#159]
Hi, I am new to flutter and have been watching the 30daysofflutter playlist and came here with a question or a feature request(if it's not only currently) which could be implemented into velocity X if possible.

On day 18, you extracted the different catalog widgets into separate widget files. so is it possible that we can do props, in the same way, using the constructor, the same way we did with names and descriptions for products/items?

`name.text.bold.$titleSize.make(),`
`desc.text.$subTitleSize.make(),`

like we define a constructor for size and when using this widget in the main widget, we can define its size, making it possible to use the same widget throughout all apps.

If this is not possible currently, could it be implemented?

**Comment by iampawan** [comment]
you can use .size() method if that's what you meant? Eg: "Hello".text.red.size(16).make()

**Comment by milindgoel15** [comment]
Ah okay. Thanks
