### ISSUE TITLE
Example app screen top margin is not right

### ISSUE THREAD

**Issue by AdiAr11** [iampawan/VelocityX#163]
**Describe the bug**
In the example app, fir first screen list's top coincides with the phone's top bar.

**To Reproduce**
Run the app on stable branch and you will see that the top margin is not right.

**Expected behavior**
The top of the screen should have some margin so that the text doesn't coincide.

**Smartphone (please complete the following information):**
 - Device:  iPhone 13

**Screenshots**
This is how it looks right now.
![Simulator Screen Shot - iPhone 13 - 2022-10-16 at 18 56 43](https://user-images.githubusercontent.com/54585121/196038406-aa99ead6-96fd-4920-b4a4-0884ee0c921b.png)

I can change it to look like this:-
![Simulator Screen Shot - iPhone 13 - 2022-10-16 at 18 57 19](https://user-images.githubusercontent.com/54585121/196038389-60a4ffa1-afb7-4644-ab35-800c3612dfc2.png)

**Comment by iampawan** [comment]
Fixed in v4.0.0
