### ISSUE TITLE
Upgrade Intl package to ^0.18.0 version

### ISSUE THREAD

**Issue by carmas123** [iampawan/VelocityX#166]
Please can you upgrade Intl package to ^0.18.0 version ?

**Comment by kevinyyykc** [comment]
This is very important. If not upgrade to intl Pack 18.0. It is incompatible even we use firebase, firestore, date picker so that we have to drop this... Please upgrade it.

**Comment by iampawan** [comment]
You can override it for now but I will be pushing the update this week most probably

**Comment by iampawan** [comment]
Fixed in v4.0.0
