### ISSUE TITLE
Not compatible with flutter 3.7

### ISSUE THREAD

**Issue by Bojacnik** [iampawan/VelocityX#180]
**Describe the bug**
Will VelocityX support flutter 3.7 in the future?
It would appear that it supports flutter 3.10 but the constraints do not exclude 3.7.
Will it be backwards compatible in the future?

**To reproduce**
run command `flutter test`

**Expected behavior**
It is supposed to work on flutter 3.7.0

**Error Snippets**
**Example 1**
Error: The getter 'View' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'View'.
  FlutterView get view => View.of(this);
  
  **Example 2**
  Error: The getter 'View' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/opt/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'View'.
  FlutterView? get maybeView => View.maybeOf(this);
  
  **Example 3**
../../.pub-cache/hosted/pub.dev/velocity_x-4.1.0/lib/src/flutter/flex.dart:51:8: Error: A constant constructor can't call a non-constant super constructor.
  }) : super(

**Package**
 - Version 4.1.0

**Desktop:**
 - OS: 6.1.30-1-MANJARO

**Smartphone**
 - Device: Pixel 3
 - OS: Android 13.0

**Additional context**

**Comment by iampawan** [comment]
This is happening because of the inclusion of https://github.com/flutter/flutter/pull/118004 and VelocityX just started using it. And because it was added during one of the Flutter 3.7 versions, it should be supported already. However, I want to keep all these versions so working on a change and it should be fixed with VelocityX v4.1.1

**Comment by iampawan** [comment]
Looks like this change should go and I highly recommend everyone to update to the latest SDK version
