### ISSUE TITLE
Remove elementAtOrNull

### ISSUE THREAD

**Issue by chems17** [iampawan/VelocityX#181]
Please remove `elementAtOrNull`
from this:
https://github.com/search?q=repo%3Aiampawan%2FVelocityX%20elementAtOrNull&type=code

This method is not longer needed because flutter already has this method:
https://api.flutter.dev/flutter/package-collection_collection/IterableExtension/elementAtOrNull.html

By the way the method in VelocityX does not work as correctly as the one in Flutter.
Regards

**Comment by iampawan** [comment]
Fixed with v4.1.1
