### ISSUE TITLE
[velocity_x 4.1.0] Range error is triggered by .capitalize function.

### ISSUE THREAD

**Issue by TLopert** [iampawan/VelocityX#182]
**Describe the bug**
Range error is triggered by .capitalize function.

**To Reproduce**
Use .capitalize function on text that ends or starts with empty space "test " or " test ".

Error:
The following RangeError was thrown building HomePage(dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#29517]], state: _HomePageState#d412d):
RangeError (index): Invalid value: Valid value range is empty: 0

**Expected behavior**
Capitalized text is returned.

**Desktop (please complete the following information):**
 - OS: Any iOS.

**Smartphone (please complete the following information):**
- Device unrealted.

**Comment by iampawan** [comment]
Fixed with v4.1.1
