### ISSUE TITLE
conflict with GoRouter extension method context.push and contaxt.pop

### ISSUE THREAD

**Issue by Eleaus-Hossain-Evan** [iampawan/VelocityX#185]
### I got a conflict error between GoRouter and VelocityX extension method push and pop.

I'm using GoRouter as my main package for routing for 1 year and recently I know about VelocityX through youtube and am willing to use it. but, after using it, it got this error on the same page where VelocityX and GoRouter exist. 

`A member named 'push' is defined in extension 'GoRouterHelper' and extension 'VxContextExtensions', and none are more specific.
Try using an extension override to specify the extension you want to be chosen`

![Screenshot 2023-07-23 172455](https://github.com/iampawan/VelocityX/assets/70533691/62d3612c-ba66-4d04-93bb-a89f76a08931)

So, I have no idea how to use both packages together. Can anyone give me any suggestions?

**Comment by codersangam** [comment]
Instead of using context, you can use directly
`GoRouter.of(context).push(RouteName);`

or In imports you can give alias name using "as" keyword either for GoRouter or Velocity_x.

**Comment by iampawan** [comment]
Fixed with v4.1.1
