### ISSUE TITLE
IntrinsicHeight widget issue

### ISSUE THREAD

**Issue by nirav-garach** [iampawan/VelocityX#186]
If we use IntrinsicHeight widget with Row widget to make each child same height then use "".text.make() Text widget or any VxWidget then it's throwing exception. Please check this issue

IntrinsicHeight(
          child: Row(
            children: [
              _leftRow(),
              "some text".text.make(),
              Container(
                padding: const EdgeInsets.only(top: 20, bottom: 20),
                child: const VerticalDivider(),
              ),
              Expanded(child: _rightRow())
            ],
          ),
        )

**Comment by iampawan** [comment]
In that case. You can use "isIntrinsic" with text widget like
"Hello".text.isIntrinsic.make(). let me know if it works for you

**Comment by nirav-garach** [comment]
Working Now Thanks.
