### ISSUE TITLE
Remove clipBehavior from OverflowBar in 3.20.0.11.0.pre66

### ISSUE THREAD

**Issue by wind-flow** [iampawan/VelocityX#200]
Remove clipBehavior in Overflow_bar.

lib > src > flutter > flex.dart in velocity_x-4.1.2.

below is error message when build.

..AppData/Local/Pub/Cache/hosted/pub.dev/velocity_x-4.1.2/lib/src/flutter/flex.dart:454:7: Error: No named parameter with the name 'clipBehavior'.
      clipBehavior: clipBehavior,
      ^^^^^^^^^^^^
../../flutter_windows_3.7.4-stable/flutter/packages/flutter/lib/src/widgets/overflow_bar.dart:57:9: Context: Found this candidate, but the arguments don't match.
  const OverflowBar({
        ^^^^^^^^^^^

**Comment by kayatechindia** [comment]
i am also facing the same issue

**Comment by abhiplxi** [comment]
pub.dev/velocity_x-4.1.2/lib/src/flutter/flex.dart:454:7: Error: No named parameter with the name 'clipBehavior'.
      clipBehavior: clipBehavior,

I'm also facing  this issue

**Comment by TruongVanTamm** [comment]
i am also facing the same issue

**Comment by esperaking81** [comment]
I have the same issue

**Comment by Comfie** [comment]
I am also facing the same issue, when I try to build project on Mac, but windows works fine

**Comment by iampawan** [comment]
Fixed in v4.2.0
