### ISSUE TITLE
[BUG]: Unable to fetch newest version VelocityX on Flutter 3.22.0

### ISSUE THREAD

**Issue by AdamHavlicek** [iampawan/VelocityX#203]
**Describe the bug**
Unable to fetch newest version VelocityX package on Flutter 3.22.0 because of pinned version of intl version 0.18.3 in VelocityX. flutter_localizations uses intl version 0.19.0 which is pinned by flutter sdk.

**To Reproduce**
upgrade to newest version of flutter. 
add flutter_localizations as your dependency.
add velocity_x as dependency.

**Expected behavior**
bump version of intl package 

**Temporary fix**
downgrade version of VelocityX to version 4.1.1

**Comment by ShafiqSadat** [comment]
+1

**Comment by esperaking81** [comment]
The temporary fix I found is to add :
```yaml
dependency_overrides:
   intl: ^0.19.0 
```

**Comment by ShafiqSadat** [comment]
also for me temporary fix not working...

**Comment by ShafiqSadat** [comment]
Temporary fix : 

  velocity_x:
    git:
      url: https://github.com/ShafiqSadat/VelocityX.git

**Comment by iampawan** [comment]
I will fix it asap.

**Comment by iampawan** [comment]
Fixed in v4.2.0
