### ISSUE TITLE
Flutter 3.22.0

### ISSUE THREAD

**Issue by Flutter05** [iampawan/VelocityX#204]
/C:/Users/Owner/AppData/Local/Pub/Cache/hosted/pub.dev/velocity_x-4.1.2/lib/src/flutter/flex.dart:454:7: Error: No named parameter with the name 'clipBehavior'.
      clipBehavior: clipBehavior,
      ^^^^^^^^^^^^

**Comment by TruongVanTamm** [comment]
Plz, have any update ?

**Comment by iampawan** [comment]
Fixed in v4.2.0
