### ISSUE TITLE
I have updated my flutter sdk and then Error: No named parameter with the name 'clipBehavior'.       clipBehavior: clipBehavior,       ^^^^^^^^^^^^

### ISSUE THREAD

**Issue by MtoagF** [iampawan/VelocityX#208]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iampawan** [comment]
Fixed in v4.2.0
