### ISSUE TITLE
Subject: Error: WidgetState not defined for _HoverToggleState in velocity_x 4.2.0

### ISSUE THREAD

**Issue by blackholeofuniverse** [iampawan/VelocityX#211]
Description:

I'm encountering an error when using the velocity_x package (version 4.2.0) in my Flutter project. The error occurs when running the app in debug mode and is related to the WidgetState getter within the _HoverToggleState class.

Here's the specific error message:
`../../../../AppData/Local/Pub/Cache/hosted/pub.dev/velocity_x-4.2.0/lib/src/flutter/hover.dart:31:42: Error: The getter 'WidgetState' isn't defined for the class '_HoverToggleState'.
 - '_HoverToggleState' is from 'package:velocity_x/src/flutter/hover.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dev/velocity_x-4.2.0/lib/src/flutter/hover.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
        onEnter: (_) => setMaterialState(WidgetState.hovered, true),
                                         ^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/velocity_x-4.2.0/lib/src/flutter/hover.dart:32:41: Error: The getter 'WidgetState' isn't defined for the class '_HoverToggleState'.
 - '_HoverToggleState' is from 'package:velocity_x/src/flutter/hover.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dev/velocity_x-4.2.0/lib/src/flutter/hover.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
        onExit: (_) => setMaterialState(WidgetState.hovered, false),
                                        ^^^^^^^^^^^`
                                        
Steps to Reproduce:

Install the velocity_x package (version 4.2.0) in a Flutter project.
Run the app in debug mode.
Expected Behavior:

The app should launch successfully without any errors.

Actual Behavior:

The app fails to launch due to the WidgetState error mentioned above.

Additional Information:

I have tried updating velocity_x to the latest version using flutter pub upgrade velocity_x, but the issue persists.
I am using Flutter version 3.19.2.
Request:

I would appreciate it if you could investigate this issue and provide a fix or workaround. If possible, please let me know if there's a known issue with WidgetState in velocity_x 4.2.0.

Thank you for your time and assistance.
![image](https://github.com/iampawan/VelocityX/assets/129941400/8eff8539-e49d-467c-8a34-17b6edadd4d8)

**Comment by JayShreeKrishna9** [comment]
hey , I am also facing the same issue in Both Version velocity_x: ^4.1.1 And velocity_x: ^4.2.0

**Comment by Bhargavp44445** [comment]
same issue

**Comment by iampawan** [comment]
It will be fixed today. Mostly happening because of older Flutter version

**Comment by iampawan** [comment]
Fixed with v4.2.1
