### ISSUE TITLE
What is the performance penalty of this sugar? 

### ISSUE THREAD

**Issue by erluxman** [iampawan/VelocityX#23]
This isn't but it does not feature either but related to performance so I made this issue.

This library is awesome and it's no brainer that there should be an easier way to implement easy stuff like padding, opacity, margin, transform etc than having to increase the height of the Christmas tree. But I have a curiosity regarding performance issues, how the internals are designed to address this aspect.

So as we make extensive use of (extension) functions in this library (at least in my understanding), what are we losing in terms of performance that we gained using StatelessWidget? 

As per this answer from  Remi Rousselet (https://github.com/rrousselGit, we might be losing some performance using functions in place of stateless Widget? 

If we are losing performance, do you have anything planned to address this issue?

**Comment by iampawan** [comment]
No we are not losing any performance because most of the times you will just use the props which are not widgets. When you say make() that means that it created one widget for you. It's almost how you write your apps but the approach is just different

**Comment by erluxman** [comment]
Thats great to hear then :)
