### ISSUE TITLE
Request for Tutorial on Vscode Extension.

### ISSUE THREAD

**Issue by Chetan11-dev** [iampawan/VelocityX#28]
Namaste Pawan,
I am so happy to send you this mail, I am so greatful for the good work you do and I learnt so much from you. Your velocityX project is totally awesome.
I am Chetan Jain and have create a Vscode extension that has helped 118 people in past 8 days and I would be really happy if you could make a tutorial upon it as I believe your aim is to help which really concides with the aim I built the extension
https://marketplace.visualstudio.com/items?itemName=ChetanJain.flutter-code-generator
Once again Thank you Pawan. Looking forward to hear from you.
Reagards,
Chetan Jain

**Comment by iampawan** [comment]
Not relevant to this lib
