### ISSUE TITLE
Widgets Matching Tailwind

### ISSUE THREAD

**Issue by Prn-Ice** [iampawan/VelocityX#29]
**Is your feature request related to a problem? Please describe.**
I am using this plugin in conjunction with the liquid_ui package, but I feel like this could be both.

**Describe the solution you'd like**
What I get from the liquid UI are the Buttons, Forms, Badges, Expansion Tiles, etc.
Since this package is inspired by tailwind, maybe we could add some of these widgets matching the tailwind style.
I and others who use this plugin will be ready to help I'm sure .

**Comment by iampawan** [comment]
The purpose of this lib is to provide useful extensions or widgets which doesn't exist and also to reduce the repetitive work which needs to be done. Premade widgets that can be easily done with existing widgets are not something we are targeting as of now.
