### ISSUE TITLE
Pass styles as parameters

### ISSUE THREAD

**Issue by Prn-Ice** [iampawan/VelocityX#30]
**Is your feature request related to a problem? Please describe.**
I find myself often in situations like 
```dart
'New Guy'.text.xl4.bold.white.make(),
'We haven\'t seen you around before'.text.xl4.bold.white.center.make(),
```

**Describe the solution you'd like**
It would be nice if we could share styles like
```dart
final style = xl4.bold.white;
'New Guy'.text.style(style).make(),
'We haven\'t seen you around before'.text.style(style).center.make(),
```

**Comment by iampawan** [comment]
There is a method called textStyle() which you can use for the same job.
