### ISSUE TITLE
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-1.0.0/lib/src/extensions/context_ext.dart:132:31: Error: The getter 'TextSelectionTheme' isn't defined for the class 'BuildContext'.  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextSelectionTheme'.   Color get selectionColor => TextSelectionTheme.of(this).selectionColor;                               ^^^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by ravikovind** [iampawan/VelocityX#35]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-1.0.0/lib/src/extensions/context_ext.dart:132:31: Error: The getter 'TextSelectionTheme' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextSelectionTheme'.
  Color get selectionColor => TextSelectionTheme.of(this).selectionColor;
                              ^^^^^^^^^^^^^^^^^^

**Comment by iampawan** [comment]
Updating to Flutter 1.22 should fix this as this was introduced in 1.22 and it's gonna be there now.
