### ISSUE TITLE
How to increase swiping speed in swiper example

### ISSUE THREAD

**Issue by viratshukla** [iampawan/VelocityX#36]
For example, we have large number of horizontal content to be scrolled. 
And it should be in same manner - like item should always come to middle after scrolling. Currently with swiper, it hardly scrolls 2-3 views at a time, which is really inconvenient. 

Any suggestion to increase the scrolling speed?

**Comment by viratshukla** [comment]
`[
          "Item 1".text.white.make().box.rounded.alignCenter.black.make().p4(),
          "Item 2".text.make().box.rounded.alignCenter.green500.make().p4(),
          "Item 3".text.make().box.rounded.alignCenter.blue500.make().p4(),
          "Item 4".text.make().box.rounded.alignCenter.red500.make().p4(),
          "Item 5".text.make().box.rounded.alignCenter.orange500.make().p4(),
          "Item 6".text.make().box.rounded.alignCenter.pink500.make().p4(),
          "Item 11".text.white.make().box.rounded.alignCenter.black.make().p4(),
          "Item 12".text.make().box.rounded.alignCenter.green500.make().p4(),
          "Item 13".text.make().box.rounded.alignCenter.blue500.make().p4(),
          "Item 14".text.make().box.rounded.alignCenter.red500.make().p4(),
          "Item 15".text.make().box.rounded.alignCenter.orange500.make().p4(),
          "Item 16".text.make().box.rounded.alignCenter.pink500.make().p4(),
          "Item 21".text.white.make().box.rounded.alignCenter.black.make().p4(),
          "Item 22".text.make().box.rounded.alignCenter.green500.make().p4(),
          "Item 23".text.make().box.rounded.alignCenter.blue500.make().p4(),
          "Item 24".text.make().box.rounded.alignCenter.red500.make().p4(),
          "Item 25".text.make().box.rounded.alignCenter.orange500.make().p4(),
          "Item 26".text.make().box.rounded.alignCenter.pink500.make().p4(),
          "Item 31".text.white.make().box.rounded.alignCenter.black.make().p4(),
          "Item 32".text.make().box.rounded.alignCenter.green500.make().p4(),
          "Item 33".text.make().box.rounded.alignCenter.blue500.make().p4(),
          "Item 34".text.make().box.rounded.alignCenter.red500.make().p4(),
          "Item 35".text.make().box.rounded.alignCenter.orange500.make().p4(),
          "Item 36".text.make().box.rounded.alignCenter.pink500.make().p4(),
        ].swiper(
            height: context.isMobile ? 200 : 400,
            enlargeCenterPage: true,
            scrollDirection: Axis.horizontal),`

**Comment by iampawan** [comment]
That's what pretty much the framework offers so there is no direct way of doing it as of now. However it should just work fine when you scroll fast if you don't have heavy data.

**Comment by viratshukla** [comment]
No actually it doesn't scroll. Even with your Boxes/Container() - which are very light.
Looks like, it is property of PageView. That at most 2-3 items are scrolled. While in other like horizontal list view, items are scrolled very fast.

May be because of pageView, it's not possible.
Can we implement the same behaviour (At a time, 1 is highlighted and it should auto-scroll in middle when finger is removed from screen) with ListView?

**Comment by iampawan** [comment]
I will take a look into it. It can be a good use case. Swiper is generally
used for 9-10 items most of the time though.

**Comment by iampawan** [comment]
Added a new flag "isFastScrollingEnabled" to scroll the page view even faster. Closing on behalf of 4de9f6e50721bdb55cf57de1ed014215c5b116b1

**Comment by iampawan** [comment]
@viratshukla Can you try it now once?
