### ISSUE TITLE
[VxTextBuilder] Should have .fontWeight method to set custom weight.

### ISSUE THREAD

**Issue by AyushBherwani1998** [iampawan/VelocityX#37]
## Description

Should have .fontWeight method to set custom weight.

**Comment by guptashubham95a** [comment]
@AyushBherwani1998 I want to add this method to set custom weight .

**Comment by AyushBherwani1998** [comment]
Hey @guptashubham95a , feel free to take the issue and submit a PR :D

**Comment by vijaysainagavamsi** [comment]
Hey @AyushBherwani1998  i would like the to take the issue.

**Comment by iampawan** [comment]
Fixed in aaf8eb0fe70f272698b968fe74ebd024368c4ea8
