### ISSUE TITLE
Error: No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by sayedtalha124** [iampawan/VelocityX#38]
> Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: /opt/hostedtoolcache/flutter/1.24.0-7.0.pre-dev/x64/.pub-cache/hosted/pub.dartlang.org/velocity_x-0.3.4/lib/src/flutter/appbar.dart:322:57:
Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);
                                                        ^^^^^^
/opt/hostedtoolcache/flutter/1.24.0-7.0.pre-dev/x64/packages/flutter/lib/src/material/scaffold.dart:1918:24:
Info: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {
                       ^^
Error: Compilation failed.
Compiling lib/main.dart for the Web...                              9.6s
Exception: Failed to compile application for the Web.
Error: Process completed with exit code 1.

**I am getting this error when deploying web app on firebase with github actions**
I am using velocity 1.0

**Comment by iampawan** [comment]
I think it is happening because of Flutter master channel. Can you try using the stable channel and see if it works. Also, make sure VelocityX is updated to 1.0 by deleting the old version in the cached pub folder.

**Comment by sayedtalha124** [comment]
I don't think the flutter web is on a stable channel. Anyways the issue is coming because of my github workflow.  It was running in dev  channel so I changed it to the beta channel and everything is works fine for now
