### ISSUE TITLE
no param named 'shadowColor' in 'card.dart' file. i am using flutter version 1.12.13 stable release.

### ISSUE THREAD

**Issue by zahidshaikh08** [iampawan/VelocityX#4]
class _VelocityXCardBuilder extends VelocityXWidgetBuilder<Widget>
    with
        VelocityColorMixin<_VelocityXCardBuilder>,
        VelocityPaddingMixin<_VelocityXCardBuilder>,
        VelocityRoundMixin<_VelocityXCardBuilder> {
  _VelocityXCardBuilder(
    this._child,
  ) : assert(_child != null) {
    setChildToColor(this);
    setChildToPad(this);
    setChildToRound(this);
  }
  final Widget _child;

  Color _shadowColor;
  double _elevation = 1.0;
  ShapeBorder _shape;

  _VelocityXCardBuilder color(Color val) => this..velocityColor = val;

  _VelocityXCardBuilder hexColor(String colorHex) =>
      this..velocityColor = VelocityX.hexToColor(colorHex);

  _VelocityXCardBuilder elevation(double val) => this.._elevation = val;

  _VelocityXCardBuilder get circular => this.._shape = const CircleBorder();
  _VelocityXCardBuilder get zeroCircular => this
    .._shape = const CircleBorder()
    .._elevation = 0.0;

  _VelocityXCardBuilder get zero => this.._elevation = 0.0;

  @override
  Widget make({Key key}) {
    return Card(
      key: key,
      margin: velocityPadding,
      child: _child,
      color: velocityColor ?? ThemeData().cardColor,
      clipBehavior: Clip.antiAlias,
      elevation: _elevation,
      shape: roundedValue.isNotNull
          ? RoundedRectangleBorder(borderRadius: BorderRadius.circular(roundedValue))
          : _shape,

> //      shadowColor: _shadowColor,                    
> 
> > **//<<<---- i have to comment 'shaowColor' field to run the 
> >                                                                             example project from your github repository. 
> >                                                                             line 67 in file.**

    );
  }
}

extension CardExtension on Widget {
  _VelocityXCardBuilder get card => _VelocityXCardBuilder(this);
}

**Comment by iampawan** [comment]
Yes, it's missing. I will add it soon.

**Comment by iampawan** [comment]
Fixed in stable channel and v0.1.1
