### ISSUE TITLE
Compose with standard flutter widgets

### ISSUE THREAD

**Issue by gedw99** [iampawan/VelocityX#42]
What limitations do you see with using velocityx to compose an app made up of many non velocity plugins ?

**Comment by iampawan** [comment]
Can you provide some examples? I couldn't understand it properly

**Comment by gedw99** [comment]
take for example your docs code https://velocityx.dev/docs/release-notes

it seems to be build from https://github.com/iampawan/VelocityXApp

but cant find release-notes in the code.

**Comment by iampawan** [comment]
No it’s a different private repo for now
