### ISSUE TITLE
[VxText] Add text opacity for next release?

### ISSUE THREAD

**Issue by chihuy105** [iampawan/VelocityX#48]
I'm see that the current version is not contain text Opacity so may you add it to the next release.

**Comment by iampawan** [comment]
Can you tell me why you would want it?

**Comment by xyzbilal** [comment]
you can use opacity in color property like below. 

`"String".text.maxLines(1).minFontSize(8).maxFontSize(10).ellipsis**.color(primaryTextColor.withOpacity(0.2)**).make()`

**Comment by iampawan** [comment]
Doesn't look like an issue to me. Closing it for now
