### ISSUE TITLE
no param called 'textScaleFactor' in 'selectable_text.dart'. flutter version 1.12.13

### ISSUE THREAD

**Issue by zahidshaikh08** [iampawan/VelocityX#5]
@override
  SelectableText make({Key key}) {
    return SelectableText(
      _text,
      key: key,
      textAlign: _textAlign,
      maxLines: _maxLines,
      toolbarOptions: const ToolbarOptions(copy: true, cut: true, paste: true, selectAll: true),
      onTap: _onTap,
      enableInteractiveSelection: true,
      // showCursor: true,

> //      textScaleFactor: _scaleFactor, 
> after commenting this field project will run successfully.

      style: _textStyle?.copyWith(
            color: velocityColor,
            fontSize: _fontSize ?? 14.0,
            fontStyle: _fontStyle ?? FontStyle.normal,
            fontFamily: _fontFamily,
            fontWeight: _fontWeight,
            letterSpacing: _letterSpacing ?? 0.0,
            decoration: _decoration ?? TextDecoration.none,
            height: _lineHeight,
          ) ??
          TextStyle(
            color: velocityColor,
            fontSize: _fontSize ?? 14.0,
            fontStyle: _fontStyle ?? FontStyle.normal,
            fontFamily: _fontFamily,
            fontWeight: _fontWeight,
            letterSpacing: _letterSpacing ?? 0.0,
            decoration: _decoration ?? TextDecoration.none,
            height: _lineHeight,
          ),
    );
  }

**Comment by iampawan** [comment]
I'll fix this today for the stable branch. It works fine on dev and master.

**Comment by iampawan** [comment]
Fixed in stable channel and v0.1.1
