### ISSUE TITLE
Flutter version 1.25.0-8.0.pre

### ISSUE THREAD

**Issue by coimstark** [iampawan/VelocityX#50]
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-1.0.1/lib/src/flutter/theme.dart:27:9: Error: No named parameter with the name 'isMaterialAppTheme'.
        isMaterialAppTheme: isMaterialAppTheme

**Comment by AyushBherwani1998** [comment]
Hey @coimstark, thanks for raising the issue. The `isMaterialAppTheme` was removed 7 days ago from the framework. For more details https://github.com/flutter/flutter/pull/71861. If you build is failing, I would suggest to downgrade the branch until the parameter is removed from the VelocityX.

**Comment by fluttergeek** [comment]
I downgraded to Flutter 1.22.5 and it worked again. In the meantime, I submitted a pull request.

**Comment by coimstark** [comment]
ok thanks mate, awesome jobs
