### ISSUE TITLE
Code not compiling in Flutter version 1.25.0-8.1.pre 

### ISSUE THREAD

**Issue by AniketSindhu** [iampawan/VelocityX#53]
![image](https://user-images.githubusercontent.com/57598532/103108714-dd692580-466c-11eb-9a29-11bbcdbf1893.png)

**Comment by mps01** [comment]
Same issue occurred with my project too.
Solution: Just remove isMaterialAppTheme : isMaterialAppTheme line occurrences from  3 classes that are dark theme, light theme and custom Theme in the file velocity_x-2.0.0-nullsafety.1/lib/src/flutter/theme.dart.

**Comment by iampawan** [comment]
Fixed in v1.3.1
