### ISSUE TITLE
when I am using velocity x package it shows me an error.

### ISSUE THREAD

**Issue by lkrjangid1** [iampawan/VelocityX#56]
when I am using velocity x package it shows me an error.

`
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/dom_canvas.dart:140:10
paint.shader == null
is not true

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/dom_canvas.dart 140:26                     _buildDrawRectElement
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/bitmap_canvas.dart 385:34                  drawRect
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/html/recording_canvas.dart 979:11          apply
...
====================================================================================================`

**Comment by iampawan** [comment]
Can you share more information? Where exactly you are getting it?

**Comment by lkrjangid1** [comment]
when I am run my app on the web android studio shows me this error.

**Comment by iampawan** [comment]
We need more info about the specific piece of code that throws this error

**Comment by lkrjangid1** [comment]
I find out this last night. When I use shimmer effect in my project. Android studio show me this error.

**Comment by iampawan** [comment]
This can be an issue with the web rendering. We can't do much here as of now
