### ISSUE TITLE
Add List<num> utility extension

### ISSUE THREAD

**Issue by AyushBherwani1998** [iampawan/VelocityX#58]
**Is your feature request related to a problem? Please describe.**
Currently there's no method on `List<num>` to calculate sum of the elements in the list, and we have to write for loop every time.

**Describe the solution you'd like**
List<num>.sum extension to get the sum of all the elements in the list
List<num>.minus extension to get the sum of all the elements in the list

**Additional context**
Very useful for in our application :P

**Comment by iampawan** [comment]
There is already extensions for sum, average, min & max.

**Comment by AyushBherwani1998** [comment]
Thanks, got it.
