### ISSUE TITLE
add widget tests

### ISSUE THREAD

**Issue by AyushBherwani1998** [iampawan/VelocityX#6]
Add widget tests to ensure that the widgets are rendered correctly. The tests can also be used in CI/CD. 

I would like to work on this issue.

I need a suggestion about writing the test. Should I write a different widget test for the various parameter or should I write a single widget test and include all the parameters of the widget? 

IMO, having a separate widget test for parameters can ensure that the widgets are correctly responding to the values.

**Comment by iampawan** [comment]
Yes, I would suggest writing separate tests.
