### ISSUE TITLE
VxTextField controller disposed when scroll

### ISSUE THREAD

**Issue by shinewanna** [iampawan/VelocityX#63]
**Describe the bug**
VxTextField controller disposed when scroll

**To Reproduce**
Just Scroll to bottom and up again in list

**Screenshots**
![Screen Shot 2021-01-24 at 1 39 13 PM](https://user-images.githubusercontent.com/39454969/105623662-c2472c80-5e49-11eb-8abf-2200d5380cfd.png)

In Android

**Comment by AyushBherwani1998** [comment]
Hey @shinewanna, can you share a minimal example to reproduce the bug? I was not able to reproduce the bug by having the VxTextField inside Listview and following your steps. Thanks

**Comment by shinewanna** [comment]
@ AyushBherwani1998 ListView[VxTextField(controller:controller),ListTile,..........] and scroll down and up again to reproduce the bug
