### ISSUE TITLE
Add VxTextFormField

### ISSUE THREAD

**Issue by AyushBherwani1998** [iampawan/VelocityX#66]
**Is your feature request related to a problem? Please describe.**
As of now we only have the VxTextField which provide great feature of clearing the input, but it's really hard to use with Form and TextFormField.

**Describe the solution you'd like**
Introduce a new widget VxTextFormField, which can be used with Form, or simply remove VxTextField in favor of VxTextFormField.

**Comment by iampawan** [comment]
Fixed in v3.1.0
