### ISSUE TITLE
SizeBox .w & .h percentage of their Containing box.

### ISSUE THREAD

**Issue by natgross** [iampawan/VelocityX#67]
It's great to have percentage sizes of the screen for VxBox. BUT, what good is it for nested boxes? Say if I have two boxes in an HStack, .wOneFourth and .wThreeFourths, and in those boxes I have of course more boxes/containers. I need to specify the inner boxes as percentages of their outer box, not a percentage of the entire screen.
Can we do this with the current version?
Or, am I being silly and there is a simple formula/function to do this, based on percentage of entire screen?
tnx

**Comment by iampawan** [comment]
Did you try using context.screenWidth or context.percentWidth and all
MediaQuery related operations? Does that help?

**Comment by natgross** [comment]
I don't see how that will help.
MediaQuery gives me Size of the screen, but I need size of container of inner boxes, in order to set relative size of inner boxes.

```
body:VxBox( //the outermost box
        child:HStack([
          //left side hold 2 vertical boxes
          VxBox(
            child: VStack([
              VxBox().make(),  //this box should a percentage of VxBox holding it
              VxBox().make(), //this box should a percentage of VxBox holding it
            ])
          ).purple300 .make().wThreeForth(context),
          //right side 1 box, top to bottom.
          VxBox(
            child: Container(),    
          ).green300.make().wOneForth(context)  
        ]),
      ).blue300.make()
```

**Comment by iampawan** [comment]
Ohh I got it now. Vx doesn’t restrict you for doing that. It uses the same
mechanism. You can easily do that though. You can watch my video for that
about how to get the size of a widget on MTECHVIRAL youtube channel.
