### ISSUE TITLE
Support for intl 0.17.0 

### ISSUE THREAD

**Issue by AniketSindhu** [iampawan/VelocityX#70]
**Describe the bug**
![image](https://user-images.githubusercontent.com/57598532/109884953-c9acf180-7ca3-11eb-98d2-23096ceb0b16.png)

**To Reproduce**
Velovity_x supports 0.16.1 and a lot of other packages depend on the latest intl package which causes a lot of compatibility issues with other packages.

**Comment by iampawan** [comment]
We will update it soon

**Comment by iampawan** [comment]
Fixed in version - ^2.4.0-nullsafety.0
