### ISSUE TITLE
errror

### ISSUE THREAD

**Issue by seyhadot** [iampawan/VelocityX#73]
And because no versions of firebase_auth_web match >1.0.0 <2.0.0, firebase_auth ^1.0.0 requires firebase_auth_web 1.0.0.
And because firebase_auth_web 1.0.0 depends on intl ^0.17.0 and velocity_x >=0.5.0 <2.0.0-nullsafety.0 depends on intl ^0.16.1, firebase_auth ^1.0.0 is incompatible with velocity_x >=0.5.0 <2.0.0-nullsafety.0.
So, because ecommerceapp depends on both velocity_x 1.4.1 and firebase_auth ^1.0.0, version solving failed.
pub get failed (1; So, because ecommerceapp depends on both velocity_x 1.4.1 and firebase_auth ^1.0.0, version solving failed.)

**Comment by iampawan** [comment]
Fixed in version - ^2.4.0-nullsafety.0
