### ISSUE TITLE
Add Desktop support for VxPlatform

### ISSUE THREAD

**Issue by abner** [iampawan/VelocityX#83]
**Is your feature request related to a problem? Please describe.**
Today VxPlatform only supports Android, iOS and Web.

**Describe the solution you'd like**
I would like VxPlatform to have desktop also as an option

We could add a extra generic argument to indicate the Desktop Widget type and add a abstract method  createDesktopWidget.

I'm happy to help if you agree with this proposal.

**Comment by iampawan** [comment]
Added in v3.0.0
