### ISSUE TITLE
VxTextfield error on clear

### ISSUE THREAD

**Issue by chrislaurie-io** [iampawan/VelocityX#84]
**Describe the bug**
When I press the clear icon (the x on the right)

**To Reproduce**
1.Create a VxTextField
2. Enter a value
3. Click on the x

**Expected behavior**
It should just clear

**Smartphone (please complete the following information):**
 - Device: Pixie 3 emulator
 - OS: Android
 - Null safe

**Additional context**
A runtime error is thrown inside the decodeEnvelope of the JSONMethodCodec class in the flutter/dart system. The clear does happen correctly afterwards.

E/MethodChannel#flutter/textinput( 5883): Failed to handle method call
E/MethodChannel#flutter/textinput( 5883): java.lang.IndexOutOfBoundsException: invalid selection start: 12
E/MethodChannel#flutter/textinput( 5883): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/MethodChannel#flutter/textinput( 5883): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput( 5883): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput( 5883): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 5883): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput( 5883): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput( 5883): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 5883): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/textinput( 5883): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter/textinput( 5883): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter/textinput( 5883): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 5883): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter/textinput( 5883): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by iampawan** [comment]
Fix the issue #81 #82

**Comment by iampawan** [comment]
Fixed in v3.0.0
