### ISSUE TITLE
Add hexColor

### ISSUE THREAD

**Issue by EmreSURK** [iampawan/VelocityX#90]
Hi,
Thanks for the great library. 
Parsing hex color is confusing for many developers. Most developers do not familiar with the concept of Hex numbers. 0xFF...

We can simply add `.hexColor`

`25282e` -> color

`Color c = 25282e.color` -> returns the parsed color.
`Color c = "25282e".color` -> returns the parsed color.

What do you think? 

Best.

**Comment by iampawan** [comment]
Did you try using Vx.hexToColor() or Vx.getColorFromHex(). One can return the Color and other can return int of that Color.

**Comment by EmreSURK** [comment]
Oh, 
I searched but could not find these.  :) 
Thank you for your support. 
I am closing that issue then.
