### ISSUE TITLE
[Navigator 2.0] replace function doesn't actually work as expected. 

### ISSUE THREAD

**Issue by AbhishekDoshi26** [iampawan/VelocityX#93]
`replace()` shouldn't allow moving back from the browser back button. However, when we move from Page 1 to Page 2 using `replace()`, here the back button will be disabled. Now move from Page 2 to Page 3 using `push()`. Now click back and reach to Page 2. Here, the back button will be enabled and you can reach Page 1 (which shouldn't be allowed).

**Steps to reproduce the behaviour:**
1. Move from Page1 to Page2 using `replace()`
2. Move from Page2 to Page3 using `push()`
3. Click back on Page3 and reach Page2
4. Click back once again on Page2 and you can reach Page1 (Shouldn't be allowed)

**Expected behaviour**
There should be no way to reach Page 1 if we are using replace() to move to the next page.

**Desktop (please complete the following information):**
 - OS: Windows 10 and Big Sur
 - Browser: Chrome and Edge

**Reproducible code**
https://github.com/AbhishekDoshi26/navigator_test

**Comment by AbhishekDoshi26** [comment]
@iampawan here's the issue as well as reproducible code. Please have a look as and when you can. 
Thank You.

**Comment by iampawan** [comment]
Added a hack in v3.1.0 to manipulate the issue. It is a framework issue. Test and let me know how it is behaving now
