### ISSUE TITLE
Guard routes in vxNavigator?

### ISSUE THREAD

**Issue by pragmatically-dev** [iampawan/VelocityX#97]
Is there any way to guard a route like beamer package?

**Comment by iampawan** [comment]
What does that do exactly? Can you share some example?

**Comment by pragmatically-dev** [comment]
Of course sir, thanks for take the time to reply me 

https://github.com/slovnicki/beamer/tree/master/examples/guards

BeamerDelegate(
  guards: [
    // Guard /books/* by beaming to /login if the user is unauthenticated:
    BeamGuard(
      pathBlueprints: ['/books/*'],
      check: (context, location) => context.isAuthenticated,
      beamToNamed: '/login',
    ),
  ],
  ...
),

**Comment by iampawan** [comment]
You should use something like:
```
 '/safe_route': (uri,_) {
  if (!isLoggedIn()) return VxRoutePage(pageName: "Home", child: HomePage());
  return LoginPage();
}
```
