### ISSUE TITLE
[Navigator 2.0] waitAndPush is not executing the callback

### ISSUE THREAD

**Issue by nishitdixit** [iampawan/VelocityX#99]
I'm using `velocity_x: ^3.0.0`.
I was using await on `context.vxNav.push(<Uri_of_the_screen>)` but when i add `.then(()=>someCallback());` it gets triggered immediately.
I assumed it to be returning immediately after pushing the new screen into the stack.
after going through the guide I got to know about 
`context.vxNav.waitAndPush(<Uri_of_the_screen>)` which is expected to work like `await Navigator.push(context, ...)`.
So I added callback with `.then()` method. just like_
`context.vxNav.waitAndPush(Uri.parse(MyRoutes.alertsRoute)).then((value) => registerCurrentScreenInAnalytics(currentIndex));`
but the callback registered with .then is not executing,
I'm wondering why no lines are being executed written after this statement if I use `await` instead of `.then()`.

my purpose is to trigger this callback when the user returns back to this screen back from another screen, So that the screen time tracking of the analytics remains updated.

Router widget of materialApp do not have NavigatorObserver so we need to track screens manually.
otherwise was very easy with RouteAware class.

**Comment by iampawan** [comment]
I got your issue, you must use returnAndPush in your last screen to await for waitAndPush(). I have also added the observer which will be there in latest version. You can also add listener to your VxNavigator object
